version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.8.0 
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
      - run: 
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
